### ISSUE TITLE
ShareBasket not working with Business Essentials

### ISSUE THREAD

**Issue by lacher-gmbh** [FriendsOfShopware/FroshShareBasket#15]
## Actual behaviour

    After saving a basket, the button "E-Mail" opens a new E-Mail, but don't include the link to the saved basket. 

## Expected behaviour

    I expected to see a new E-Mail open up with the link to the saved basket.

## Environment

    This only occurs in a shop using Business Essentials 3.2.2. Shopware 5.5.3 Build Rev 201810301443

## Steps to reproduce

Shop without Business Essentials - working like expected: 
![grafik](https://user-images.githubusercontent.com/52962023/61293820-d16d0900-a7d4-11e9-8f34-572032f4e53d.png)

Shop with Business Essentials - E-Mail share not working:
![grafik](https://user-images.githubusercontent.com/52962023/61293998-2dd02880-a7d5-11e9-924e-11d7a9181c8c.png)

## Checklist

- [x ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshShareBasket/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by stefanpoensgen** [comment]
i'm not able to reproduce this behavior. please provide further information of your "Business Essentials" configuration, especially template variables.

**Comment by lacher-gmbh** [comment]
this is our configuration, template variables aren't used at all.
maybe the issue comes with the "private shopping"?

![grafik](https://user-images.githubusercontent.com/52962023/61517939-ba166180-aa08-11e9-852b-05b808edd126.png)

![grafik](https://user-images.githubusercontent.com/52962023/61518038-fba70c80-aa08-11e9-8639-7d723edddbf7.png)

![grafik](https://user-images.githubusercontent.com/52962023/61517944-bda9e880-aa08-11e9-91c2-f32f3c923604.png)

**Comment by stefanpoensgen** [comment]
Even with private shopping and your settings i can not find any issues. Maybe you could give me a link to your testing environment and i will have a look into your issue.
mail@stefanpoensgen.de

**Comment by lacher-gmbh** [comment]
I actually think i found the issue myself. The generated link looks like this: `mailto:%20?subject=Mein Warenkorb von%20Dies & Das-Shop by Lacher&body=https://diesdas.lacher.de/staging/loadBasket/sjrKsUJYcNv`

I think the "&" symbol causes the problem. So it's actually a settings problem, i need to solve.
