### ISSUE TITLE
store additional Fields from Loan Plugin are not safed

### ISSUE THREAD

**Issue by zvenson** [FriendsOfShopware/FroshShareBasket#17]
## Actual behaviour

We are using this plugin for our shopware Shop. It enables clients to rent articles for a certain time. 
https://store.shopware.com/rhiem38738281933/mietartikel-artikel-vermieten.html
This time is not stored in the shared cart. I set all Fields in Backend to be stored, but these aren't stored.

## Expected behaviour

Fields from external Plugin should be stored in Cart 

## Environment

    Please provide information about the environment in which the issue occurs (e.g. PHP version, webserver, Shopware version, debugging information if you can provide).

## Steps to reproduce

1. Install both Plugins
2. Rent some Articles
3. Share Cart -

**Comment by stefanpoensgen** [comment]
This plugin stores the information in its own database tables, so it is not possible to store its information by FroshShareBasket plugin.
