### ISSUE TITLE
E-Mail Text anpassen

### ISSUE THREAD

**Issue by xinstinct** [FriendsOfShopware/FroshShareBasket#20]
Es wäre toll, wenn mann in der E-Mail nicht nur den Link sehen würde, sondern auch einen zusätzlichen Text.
Mir würde es reichen wenn ein Textbaustein vor dem Link und ein Textbaustein danach wäre.

**Comment by stefanpoensgen** [comment]
Du kannst hierzu einfach das Template überschreiben.

https://github.com/FriendsOfShopware/FroshShareBasket/blob/b2edb86de433e59d4c5284fd36869e84910d9f84/Resources/views/frontend/frosh_share_basket/save.tpl#L31
