### ISSUE TITLE
Custom Product Configuration is deleted

### ISSUE THREAD

**Issue by xspo-stephan** [FriendsOfShopware/FroshShareBasket#21]
---

## Actual behaviour

If a product with a custom product is placed in the shopping basket, the configuration of the custom product remains until the shopping basket (item with the custom product position) is deleted in the originally created browser.

## Expected behaviour

The configuration of the custom product should not be deleted when the shopping cart is loaded and the item is deleted in the created browser.

## Environment

- Shopware 5.5.10
- Nginx & Apache
- PHP Version 7.0.33-1
- "Delete shopping baskets after X months" -> "6
- "Validity of the custom products configurations:" -> "30

## Steps to reproduce

1. Go to https://www.xspo.com/atomic-redster-g9-fis
2. "Choose your binding" under the Variants
  -> "Mounting"-> "Binding mounting desired (ski boot sole length necessary)"
  -> "length of skiing boots" -> "325"
  -> "Ski level" -> "very good skiing level"
  -> "Body weight" "80"
  -> "My age" -> "between 13 and 50 years"
  -> "selecetion of ski bindings (buy as set)" -> "Atomic X 19 VAR"
3. "Add to shopping cart"
4. "Edit shopping cart"
5. "Save cart"
6. Copy and open the Url in some incognito Browser Windows
 -> The configuration remains present all the time
7. Delete the item from the shopping cart in the original browser window
8. Open the Url again in some incognito Browser Window
 -> The configuration has disappeared

## Checklist

- [ X ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshShareBasket/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ X ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Hey,

We are focusing on Shopware 6 plugins. Feel free to create a pull request if possible
