### ISSUE TITLE
Plugin Update throws error

### ISSUE THREAD

**Issue by GunnarBienek** [FriendsOfShopware/FroshShareBasket#23]
### PHP Version

7.3

### Shopware Version

5.6.1

### Actual behaviour

Hi there,
when I try to update "Warenkorb teilen" and "Variantenwechsel im Warenkorb" I get this error:
Error
Sie besitzen keine gültige Lizenz um dieses Plugin zu verwenden.

Error code: BinariesException-15

"You have no valid license for this plugin"

Thanks in Advance

Best Regards

Gunnar

### Expected behaviour

Updateing the plugins.

### Steps to Reproduce?

Click on Update button.

**Comment by shyim** [comment]
Check your store connection and maybe buy it for free in the store
