### ISSUE TITLE
Falsche Freitextfelder Tabelle

### ISSUE THREAD

**Issue by rogrconvis** [FriendsOfShopware/FroshShareBasket#24]
### PHP Version

7.4

### Shopware Version

5.7.7

### Actual behaviour

In Ihrer Config  "Zusätzliche Felder speichern", beziehen sie sich auf die Tabelle "s_order_detail_attributes". 
Aber in Ihrer Funktion "getBasketAttributes" bauen sie einen SQL-Query, der sich auf die Tabelle "s_order_basket_attributes" bezieht. Was dazu führt, dass die folgende Abfrage bei Freitextfeldern von anderen Plugins nicht ausgeführt wird.
Pfad: custom/plugins/FroshShareBasket/Components/ShareBasketService.php Zeile: 116 - 119
` if ($value && in_array($attribute, $attributesToStore, false)) {
      $basketArticle['attributes'][$attribute] = $value;
}`

### Expected behaviour

Wenn sie in ihrer Config die Tabelle  "s_order_detail_attributes" mit der Tabelle "s_order_basket_attributes" austauschen, können die entsprechenden Freitextfelder ausgewählt und die Abfrage ausgeführt werden.

### Steps to Reproduce?

Nachstellen können sie diesen Bug, mit jedem Freitextfeld welches nicht Standardmäßig von Shopware kommt.

**Comment by shyim** [comment]
Hey,

magst du ein PR machen?

**Comment by stefanpoensgen** [comment]
Ich kann hier keinen Fehler nachvollziehen.
Das Plugin funktioniert in meinen Tests genau wie vorgesehen.

Felder die in s_order_detail_attributes angelegt werden, werden von Shopware automatisch in s_order_basket_attributes angelegt. Sollten dort Felder von zusätzlichen Plugins fehlen, ist davon auszugehen das diese Plugins die Felder nicht korrekt anlegen.

![chrome_uBVuEaYwKi](https://user-images.githubusercontent.com/22468102/179389315-c001b178-2a15-4352-89d5-bd062ef35658.png)
![chrome_eEDopR17iv](https://user-images.githubusercontent.com/22468102/179389318-22d631ab-1b77-4909-95b8-ec02edb392cd.png)
