### ISSUE TITLE
Cart pricing problems 

### ISSUE THREAD

**Issue by tuami** [FriendsOfShopware/FroshShareBasket#25]
### PHP Version

7.4.30

### Shopware Version

5.5.10

### Actual behaviour

When using the FroshShareBasket plugin with the "Set Article Plugin" the prices in the shopping cart are calculated incorrectly.
https://store.shopware.com/tonur31765851076/set-artikel.html

Both plugins work independently of each other.

We have to delete the server cache, to empty the price for the basket (also when its already empty)

### Expected behaviour

Compatibility

### Steps to Reproduce?

Reproduce:

htacces
konorg|shopware

**Product without Set Article Plugin**, go to cart and click "Warenkorb teilen", copy link into new tab 
https://www.konorg-shop.de/_testumgebung/roll-up-display-basic-513

**Product with Set Article Plugin** , go to cart and click "Warenkorb teilen", copy link into new tab, reload different prices will be shown
https://www.konorg-shop.de/_testumgebung/led-messestand-modulap-one-set-cleo-1454

**Comment by stefanpoensgen** [comment]
I'm currently not planning to integrate 3rd party plugins.
