### ISSUE TITLE
LoadBasket in special controller

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshShareBasket#4]
Me likes nice urls.
`sharebasket/load/bID/[id]` isn't nice.

Maybe a different controller `loadbasket` for this, rsulting like `loadbasket/bID/[id]` ?

**Comment by dneustadt** [comment]
👍 for something nice and short

Maybe even consider inserting into `s_core_rewrite_url` and you could have `/[id]`
Those entries would have to be deleted too once saved baskets get deleted by the cron job.

**Comment by tinect** [comment]
Great idea @dneustadt 😱 
`loadBasket/OurBestProducts` 👍

**Comment by stefanpoensgen** [comment]
Thank you for the suggestion. Take a look at https://github.com/FriendsOfShopware/FroshShareBasket/commit/3d3a5c10d0a5d99779b3069f5b5af4db79200486
The URL might look like `http://shopware.localhost/loadBasket/RIVHDDS2en2`

Maybe put the "loadBasket" part into the plugin config to customize the URL.
